### ISSUE TITLE
[Feature request]: Automatic submission/voting system

### ISSUE THREAD

**Issue by talld** [campanula/game-dev-soc-bot#1]
It would be great if the bot could automate all aspects of the slow-jams.
An automatic submission/voting system would allow the bot to be set and just keep running till the end of time.

submissions like:
`+jam-submission [github OR itch.io link]` ( probably a good idea to validate these links to stop mischief ) 

then when the jam has ended it pastes all the links with 
`submission team-name: [link] ` into a voting channel
which users can then react to with set emotes to decide the winner ( which could be announced in a jam-winners channel ).

**Comment by campanula** [comment]
Voting system has been added to the bot :)
